import type { NextConfig } from "next";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

/**
 * Hosts allowed to request dev-only assets (`/_next/*`, HMR) — see
 * `allowedDevOrigins` below.
 *
 * Every RFC 1918 range is covered rather than one hard-coded address, because
 * the address in play changes constantly: Wi-Fi is on DHCP, the hotspot adapter
 * is 192.168.137.1, and a VPN adapter can add a 172.16.x.x that `next dev`
 * happens to print as its "Network" URL. Matching is per dot-segment with no
 * range syntax, so the 172.16.0.0/12 block has to be enumerated.
 *
 * Development only — `allowedDevOrigins` has no effect on `next start`.
 */
const privateNetworkOrigins = [
  "127.0.0.1",
  "10.*.*.*",
  "192.168.*.*",
  "169.254.*.*", // link-local, e.g. a direct cable or a stalled DHCP lease
  ...Array.from({ length: 16 }, (_, index) => `172.${16 + index}.*.*`),
];

const nextConfig: NextConfig = {
  /**
   * Pin the workspace root. Without this Turbopack walks up looking for a
   * lockfile and finds one in the home directory, which would drag the whole
   * of C:\Users\Mahan into the build's file tracing.
   */
  turbopack: {
    root: dirname(fileURLToPath(import.meta.url)),
  },

  images: {
    /**
     * All product and editorial art is first-party SVG generated by
     * `scripts/generate-images.ts`. The optimizer refuses SVG by default, so it
     * is enabled here and locked down with a sandbox CSP — no scripts, no
     * external references — since the files never come from user input.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy:
      "default-src 'self'; script-src 'none'; sandbox; style-src 'unsafe-inline';",
    formats: ["image/avif", "image/webp"],
  },

  /**
   * In development Next.js answers `/_next/*` with 403 whenever the request's
   * Origin/Referer host is not on this list, so opening the dev server from a
   * phone on the LAN served the HTML but no CSS and no JS chunks — an unstyled
   * page with nothing interactive. `/_next/image` is exempt from the check,
   * which is why the photographs still loaded and it read as a styling bug.
   */
  allowedDevOrigins: privateNetworkOrigins,

  experimental: {
    // Product photography is uploaded through a Server Action, so the default
    // 1 MB request cap would reject anything straight off a camera. The upload
    // itself refuses files over 6 MB (`lib/uploads.ts`); the headroom here is
    // for the multipart envelope around them.
    serverActions: { bodySizeLimit: "8mb" },
  },
};

export default nextConfig;
