// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    /**
     * Migrations need a direct connection. Managed Postgres (Neon, Supabase)
     * hands out a pooled URL for the app, but the pooler runs in transaction
     * mode and drops the advisory lock and session state that `migrate deploy`
     * relies on, so it fails there. `DIRECT_URL` carries the unpooled string
     * when the two differ; locally there is no pooler and it stays unset.
     */
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
